services:

  rabbitmq: 
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dataingestor:
    image: ${DOCKER_REGISTRY-}dataingestor
    build:
      context: .
      dockerfile: DataIngestor/Dockerfile

  dataprocessor.api:
    image: ${DOCKER_REGISTRY-}dataprocessorapi
    build:
      context: .
      dockerfile: DataProcessor/DataProcessor.Api/Dockerfile

  apigateway.api:
    image: ${DOCKER_REGISTRY-}apigatewayapi
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway.Api/Dockerfile

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile

volumes:
  rabbitmq-data:

