// <auto-generated />
using System;
using DataProcessor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataProcessor.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    partial class TelemetryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataProcessor.Domain.Entities.AirQualityMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Co2")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Pm25")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "CreatedAt");

                    b.ToTable("air_quality_metrics", (string)null);
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.EnergyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Energy")
                        .HasColumnType("real");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "CreatedAt");

                    b.ToTable("energy_metrics", (string)null);
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Corridor"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Garage"
                        });
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.MotionMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("MotionDetected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "CreatedAt");

                    b.ToTable("motion_metrics", (string)null);
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.AirQualityMetric", b =>
                {
                    b.HasOne("DataProcessor.Domain.Entities.Location", "Location")
                        .WithMany("AirQualityMetrics")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.EnergyMetric", b =>
                {
                    b.HasOne("DataProcessor.Domain.Entities.Location", "Location")
                        .WithMany("EnergyMetrics")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.MotionMetric", b =>
                {
                    b.HasOne("DataProcessor.Domain.Entities.Location", "Location")
                        .WithMany("MotionMetrics")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DataProcessor.Domain.Entities.Location", b =>
                {
                    b.Navigation("AirQualityMetrics");

                    b.Navigation("EnergyMetrics");

                    b.Navigation("MotionMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
